import React from 'react';
import { JetBrains_Mono } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';
import PageTransition from '@/components/PageTransition';
import StairTransition from '@/components/StairTransition';
import Footer from '@/components/Footer';
import CircularTextWithButton from '../components/CircularTextBtn'; // Import the CircularTextWithButton component

const jetbrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
  variable: '--font-jetbrainsMono',
});

export const metadata = {
  title: 'arif-ahmmad-sumon',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${jetbrainsMono.variable} relative`}>
        {/* Move CircularTextWithButton to the top */}
        <div className="absolute  top-[60vh]  left-20 m-10 transform -translate-x-1/2 z-10 hidden xl:block">
          <CircularTextWithButton />
        </div>
        
        <Header />
        <StairTransition />
        <PageTransition>
          {children}
        </PageTransition>
      </body>
    </html>
  );
}
