import React from "react";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/StairTransition";
import CircularTextWithButton from "../components/CircularTextBtn";
import { ThemeProvider } from "@/components/theme-provider";
import LightRays from "@/components/LightRays";
import MobileHyperspeedWrapper from "@/components/MobileHyperspeedWrapper"; // ✅ Added

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetbrainsMono",
});

export const metadata = {
  title: "arif-ahmmad-sumon",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${jetbrainsMono.variable} relative`}>
        {/* ✅ Backgrounds */}
        {/* Desktop background */}
        <div
          className="absolute inset-0 -z-10 hidden md:block"
          style={{
            width: "100%",
            height: "100%",
            overflow: "hidden",
            pointerEvents: "none",
          }}
        >
          <LightRays
            raysOrigin="top-center"
            raysColor="#00ffff"
            raysSpeed={1.5}
            lightSpread={0.8}
            rayLength={1.2}
            followMouse={true}
            mouseInfluence={0.1}
            noiseAmount={0.1}
            distortion={0.05}
            className="custom-rays"
          />
        </div>

        {/* ✅ Mobile Hyperspeed Background */}
        <MobileHyperspeedWrapper />

        {/* Floating circular button */}
        <div className="absolute top-[60vh] left-20 m-10 transform -translate-x-1/2 z-10 hidden xl:block">
          <CircularTextWithButton />
        </div>

        {/* Header + Page transitions */}
        <Header />
        <StairTransition />
        <PageTransition>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </PageTransition>
      </body>
    </html>
  );
}
